# Generated by Django 4.1.2 on 2022-10-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_is_active'),
        ('acme_admin', '0002_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_department',
            field=models.ForeignKey(blank=True, help_text='Assign Department for Users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='acme_admin.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_roles',
            field=models.ForeignKey(blank=True, help_text='Assign roles for users', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
