# Generated by Django 4.1.2 on 2022-10-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_admin', '0005_alter_customuser_options_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
